services:
    bite_codes_monolog_ui.handler.doctrine_dbal_handler:
        class: BiteCodes\MonologUIBundle\Handler\DoctrineDBALHandler
        arguments:
            - '@doctrine.dbal.monolog_connection'
            - '%bitecodes_monolog_ui.doctrine.table_name%'
            - '%bitecodes_monolog_ui.logger.handles%'

    bite_codes_monolog_ui.model.log_repository:
        class: BiteCodes\MonologUIBundle\Model\LogRepository
        arguments: ['@doctrine.dbal.monolog_connection', '%bitecodes_monolog_ui.doctrine.table_name%']

    monolog.processor.psr_log_message_processor:
        class: Monolog\Processor\PsrLogMessageProcessor
        tags:
            - { name: monolog.processor }